# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

judges = User.create! [{:username => "PeoPiCaprio",
                       :password => "password",
                       :judge => true },
                      {:username => "BobbyJeNiro",
                       :password => "password",
                       :judge => true },
                      {:username => "IuliiaRoberts",
                       :password => "password",
                       :judge => true },
                      {:username => "ZackMephron",
                       :password => "password",
                       :judge => true },
                      {:username => "MarkSahlberg",
                       :password => "password",
                       :judge => true },
                      {:username => "RyanJosling",
                       :password => "password",
                       :judge => true }]

users = 20.times.map do
  User.create!( :username => Faker::Internet.user_name,
                :judge => false,
                :password => 'password' )
end

categories = Category.create! [{:name => "Drama"},
                               {:name => "Comedy"},
                               {:name => "Thriller/Horror"},
                               {:name => "Musical"},
                               {:name => "Action/Adventure"},
                               {:name => "Documentary"}]

films = Film.create! [{:title => "The Panshank Redemption",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                      {:title => "Saving Private Ryan Jafari",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                      {:title => "WALL*ST",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Hello World!",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Monty Python vs Rails",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Hunger Games: Catching Firey Skippers",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Dark Nighthawks",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Planet of the Pocket Gophers",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "School of Rock Doves",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Old Man and the Sea Lions",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Peter Pan Wangperawong",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Squirrel of Wall Street",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "To Kill a Rock Dove",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Pan Fiction",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "I Am Sam Blackman",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Harry Potter and the Philosopher's Ruby Gem",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Eat, Pray, CRUD",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Guardians of the Github",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Big Heroku 6",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "21 Wall Street",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Fault in Our Rspec",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Inside Out TDD",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Mission:Impossible Sudoku Challenge",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Master of Merge Conflicts",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Sealion King",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Fantastic Mr. Island Foxes",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "500 Days of DBC",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Julia and Iuliia",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "Pirates of the...Don't Torrent Here",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)},
                       {:title => "The Ruby and Beast",
                       :user_id => rand(1..26),
                       :category_id => rand(1..6)}]

ratings = 30.times.map do
  Rating.create!( :score => rand(1..10),
                  :user_id => rand(1..26),
                  :film_id => rand(1..30) )
end

reviews = 30.times.map do
  Review.create!( :body => Faker::Lorem.sentence,
                  :user_id => rand(7..26) )
end